# Site settings
author: Desmond W.
title: Grumpy Analysis
header-img: img/home-bg.png
email: webbdesmondj@gmail.com
copyright_name: Desmond W.
description: > # this means to ignore newlines until "baseurl:"
  Musings of a fledgling data scientist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Neji128

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
